# Generated by Django 3.0.4 on 2020-03-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('auto_increment_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
