# Generated by Django 2.1 on 2018-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180807_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='auto_increment_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
