# Generated by Django 2.1 on 2018-08-16 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180807_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
